# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_JoyStickControl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_JoyStickControl.setGeometry(QtCore.QRect(50, 40, 181, 71))
        self.pushButton_JoyStickControl.setObjectName("pushButton_JoyStickControl")
        self.pushButton_AutoNavig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_AutoNavig.setGeometry(QtCore.QRect(50, 130, 181, 71))
        self.pushButton_AutoNavig.setObjectName("pushButton_AutoNavig")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_JoyStickControl.setText(_translate("MainWindow", "Joy Stick Control"))
        self.pushButton_AutoNavig.setText(_translate("MainWindow", "Autonomous Navigation"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
