# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.commandLinkButton_Dissconnect = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_Dissconnect.setGeometry(QtCore.QRect(680, 520, 177, 41))
        self.commandLinkButton_Dissconnect.setObjectName("commandLinkButton_Dissconnect")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 861, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_ConnectToRobot = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_ConnectToRobot.setObjectName("pushButton_ConnectToRobot")
        self.horizontalLayout_3.addWidget(self.pushButton_ConnectToRobot)
        self.pushButton_Rviz2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_Rviz2.setObjectName("pushButton_Rviz2")
        self.horizontalLayout_3.addWidget(self.pushButton_Rviz2)
        self.pushButton_Record = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_Record.setObjectName("pushButton_Record")
        self.horizontalLayout_3.addWidget(self.pushButton_Record)
        self.pushButton_RQt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_RQt.setObjectName("pushButton_RQt")
        self.horizontalLayout_3.addWidget(self.pushButton_RQt)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 861, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Autonomous = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Autonomous.setObjectName("pushButton_Autonomous")
        self.horizontalLayout.addWidget(self.pushButton_Autonomous)
        self.pushButton_JoyControl = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_JoyControl.setObjectName("pushButton_JoyControl")
        self.horizontalLayout.addWidget(self.pushButton_JoyControl)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 421, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_NewMap = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_NewMap.setObjectName("pushButton_NewMap")
        self.horizontalLayout_2.addWidget(self.pushButton_NewMap)
        self.pushButton_withMap = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_withMap.setObjectName("pushButton_withMap")
        self.horizontalLayout_2.addWidget(self.pushButton_withMap)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 330, 611, 121))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(650, 360, 191, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_StartStopRecord = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_StartStopRecord.setGeometry(QtCore.QRect(650, 430, 191, 41))
        self.pushButton_StartStopRecord.setObjectName("pushButton_StartStopRecord")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.commandLinkButton_Dissconnect.setText(_translate("MainWindow", "Dissconnect Robot"))
        self.pushButton_ConnectToRobot.setText(_translate("MainWindow", "Connect to ROBOT"))
        self.pushButton_Rviz2.setText(_translate("MainWindow", "Rviz2"))
        self.pushButton_Record.setText(_translate("MainWindow", "Record  Bag File"))
        self.pushButton_RQt.setText(_translate("MainWindow", "RQt"))
        self.pushButton_Autonomous.setText(_translate("MainWindow", "Autonomous"))
        self.pushButton_JoyControl.setText(_translate("MainWindow", "Joy Stick Contro"))
        self.pushButton_NewMap.setText(_translate("MainWindow", "New Map"))
        self.pushButton_withMap.setText(_translate("MainWindow", "Select Map"))
        self.label.setText(_translate("MainWindow", "Please"))
        self.pushButton_StartStopRecord.setText(_translate("MainWindow", "Strart Recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
